root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
env:
  browser: true
  es2021: true
  node: true
  mocha: true
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - plugin:@typescript-eslint/recommended
  - 'prettier'
