---
variables:
  SAST_EXCLUDED_PATHS: public,vendor,node_modules

cache:
  paths:
    - vendor/
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - yarn install
    - yarn global add gulp
    - gulp build

test:
  stage: test
  script: echo "Testing..."

deploy:
  stage: deploy
  script: echo "Deploying..."

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
