---
ci:
  collect:
    numberOfRuns: 3
    startServerCommand: yarn run ci
    url:
      - http://localhost:1234/
  assert:
    preset: lighthouse:recommended
  upload:
    target: temporary-public-storage
