-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 10:24:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crouzet_pricing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crouzet_pricing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crouzet_pricing` DEFAULT CHARACTER SET utf8 ;
USE `crouzet_pricing` ;

-- -----------------------------------------------------
-- Table `crouzet_pricing`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crouzet_pricing`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `part_number` VARCHAR(45) NOT NULL,
  `tracked_since` DATE NOT NULL,
  `tracked_end` DATE NULL DEFAULT NULL,
  `last_check` DATE NULL DEFAULT NULL,
  `update_interval` INT(11) NOT NULL DEFAULT 7,
  `state` ENUM('OK', 'PENDING', 'ERROR') NOT NULL DEFAULT 'PENDING',
  `manufacturer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `part_number_UNIQUE` (`part_number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `crouzet_pricing`.`prices_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crouzet_pricing`.`prices_history` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `part_number` VARCHAR(45) NOT NULL,
  `date_checked` DATE NOT NULL,
  `price` FLOAT NOT NULL,
  `supplier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_part_number_idx` (`part_number` ASC),
  CONSTRAINT `fk_part_number`
    FOREIGN KEY (`part_number`)
    REFERENCES `crouzet_pricing`.`products` (`part_number`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `crouzet_pricing`.`product_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crouzet_pricing`.`product_match` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `part_number` VARCHAR(45) NOT NULL,
  `replacement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_part_number_idx` (`part_number` ASC),
  INDEX `fk_replacement_idx` (`replacement` ASC),
  CONSTRAINT `fk_match_part_number`
    FOREIGN KEY (`part_number`)
    REFERENCES `crouzet_pricing`.`products` (`part_number`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_match_replacement`
    FOREIGN KEY (`replacement`)
    REFERENCES `crouzet_pricing`.`products` (`part_number`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `crouzet_pricing`.`stock_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crouzet_pricing`.`stock_history` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `part_number` VARCHAR(100) NOT NULL,
  `date_checked` DATE NOT NULL,
  `stock` VARCHAR(100) NOT NULL,
  `supplier` VARCHAR(100) NOT NULL,
  `state` ENUM('OK', 'PENDING', 'ERROR') NOT NULL DEFAULT 'PENDING',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `stock_history_un` (`id` ASC),
  INDEX `stock_history_fk` (`part_number` ASC),
  CONSTRAINT `stock_history_fk`
    FOREIGN KEY (`part_number`)
    REFERENCES `crouzet_pricing`.`products` (`part_number`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `crouzet_pricing`;

DELIMITER $$
USE `crouzet_pricing`$$
CREATE
DEFINER=`pricing_user`@`localhost`
TRIGGER `crouzet_pricing`.`when_new_stock`
AFTER INSERT ON `crouzet_pricing`.`stock_history`
FOR EACH ROW
begin
	update crouzet_pricing.products
	set
		last_check = new.date_checked,
		state = new.state
	where part_number = new.part_number;
end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
